### PR TITLE
fix bugs of Input handle and enable Travis CI

### PR DESCRIPTION
**Pull request by parai**

### CODE REVIEW

**Comment by parai** [comment]
Hi @majianjia :
I think it's better to enable the CI on Travis to run some test on the cloud for each PR to avoid some bugs or issues.
Check this https://travis-ci.org/autoas/nnom, I enabled a test of mnist model, which will do  train and try to convert the keras model to nnom model and build.
This is good to avoid errors.
I think we can go on to extend the test.

please register an account on https://travis-ci.org/account/repositories and enable it for your repository.

image

**Comment by majianjia** [comment]
Done, thanks for the instruction

**Comment by majianjia** [comment]
It looks not right in the master after merging. could you check later?
https://travis-ci.org/majianjia/nnom

**Comment by parai** [comment]
It's resulted by the change of CMSIS NN, they add a new file https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.c

**Pull request merged**
